const SUPABASE_URL = 'https://lvdoaekdwocierlzjmsu.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2ZG9hZWtkd29jaWVybHpqbXN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwMjM3MzUsImV4cCI6MjA5MDU5OTczNX0.7FpIGeLn5JGXlgWtfLwIuGKdMgaVC9VSGda2NONCd0Y';
const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);